name: Android CI

on: push
jobs:

  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build debug APK
        run: bash ./gradlew assembleDebug -x detektAll --stacktrace

  tests:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: bash ./gradlew test --stacktrace

  tasks:
    needs: [prepare, tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: display all tasks
        run: bash ./gradlew tasks --stacktrace

  build:
    needs: [prepare, tests, tasks]
    runs-on: ubuntu-latest
    steps:
      - name: Build debug APK
        run: bash ./gradlew assembleDebug -x detektAll --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
