name: Android CI

on: push
jobs:

  qemu:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: false
            tags: user/app:latest

  prepare:
    needs: [ qemu ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  tests:
    needs: [ prepare, qemu ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: bash ./gradlew test --stacktrace

  tasks:
    needs: [ prepare, tests, qemu ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: display all tasks
        run: bash ./gradlew tasks --stacktrace

  build:
    needs: [ prepare, tests, tasks, qemu ]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Build debug APK
        run: bash ./gradlew assembleDebug -x detektAll --stacktrace
