name: Android CI

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: docker build -t test-docker-image:latest .

      - name: Run Docker container
        run: |
          if docker ps -a --filter "name=test-container-name" --format "{{.Status}}" | grep -q "Exited"; then
            docker start test-container-name
            echo "Container 'test-container-name' was stopped, restarted."
          elif [ -z "$(docker ps -q --filter "name=test-container-name")" ]; then
            docker run -d --name test-container-name test-docker-image:latest
            echo "Container 'test-container-name' didn't exist, created."
          else
            echo "Container 'test-container-name' is already running."
          fi
      - name: Execute ./gradlew assembleDebug
        run: docker exec test-container-name /app/gradlew assembleDebug -x detektAll

      - name: Clean up
        run: |
          docker stop test-container-name
          docker rm test-container-name
