name: Android CI

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: docker build -t test-docker-image:latest .

      - name: Run Docker container
        run: docker run -d --name test-container-name test-docker-image:latest

      - name: Execute ./gradlew assembleDebug
        run: docker exec test-container-name ./gradlew assembleDebug -x detektAll

      - name: Clean up
        run: |
          docker stop test-container-name
          docker rm test-container-name
