name: Android CI

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --platform linux/arm64/v8 -t test-docker-image:latest .

      - name: Stop and remove existing container (if any)
        run: |
          docker stop test-container-name || true
          docker rm test-container-name || true

      - name: Run Docker container
        run: docker run -ti -d --name test-container-name --memory=16g test-docker-image:latest

      - name: Install AppCenter
        run: docker exec test-container-name npm install -g appcenter-cli

      - name: Upload apk to AppCenter
        run: docker exec test-container-name appcenter distribute release --app deadrudolph/Mad-Bard

      - name: Clean up
        run: |
          docker stop test-container-name
          docker rm test-container-name

