name: Android CI

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: docker build --platform linux/arm64/v8 -t test-docker-image:latest .

      - name: Stop and remove existing container (if any)
        run: |
          docker stop test-container-name || true
          docker rm test-container-name || true

      - name: Run Docker container
        run: docker run -ti -d --name test-container-name --memory=16g test-docker-image:latest

      - name: Stop gradle
        run: docker exec test-container-name /app/gradlew --stop

      - name: Upload apk to AppCenter
        env:
          appName: "Mad-Bard"
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: "/app/app/build/outputs/apk/debug/app-debug.apk"
        run: |
          chmod +x ./app/scripts/deploy/upload_build_to_appcenter
          app/scripts/deploy/upload_build_to_appcenter

      - name: Clean up
        run: |
          docker stop test-container-name
          docker rm test-container-name

