name: Android CI

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: docker build -t test-docker-image:latest .

      - name: Stop and remove existing container (if any)
        run: |
            docker stop test-container-name || true
            docker rm test-container-name || true

      - name: Run Docker container
        run: docker run -d --name test-container-name test-docker-image:latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Execute gradlew assembleDebug
        run: |
          docker run \
            --rm \
            -v $(pwd):/app \
            -w /app \
            test-docker-image \
            ./gradlew assembleDebug -x detektAll

      - name: Clean up
        run: |
          docker stop test-container-name
          docker rm test-container-name
